name: pawpress
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  cupertino_icons: ^1.0.8
  firebase_dynamic_links: ^6.1.7
  url_launcher: ^6.2.5
  http: ^1.4.0
  flutter_paypal: ^0.2.1
  file_selector: ^0.9.3
  image_picker: ^1.0.7
  shared_preferences: ^2.5.3
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  provider: ^6.1.5
  app_links: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/couple.png
    - assets/clouds.png
    - assets/profile.png
    - assets/cat1.png
    - assets/google.png
    - assets/couchguy.png
    - assets/catFood.png
    - assets/dogToy.png
    - assets/Bird.png
    - assets/Fish.png
    - assets/paw.png
    - assets/mapImage.jpeg
    - assets/online-shop.png
